# frozen_string_literal: true

# This file was generated by Bundler.

#
# The application 'rspec' is installed as part of a gem, and
# this file is here to facilitate running it.
#
module ApplicationHelper
  def desc(object)
    object.order('id DESC')
  end
end
